package exo1;


/**
* exo1/calculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* Tuesday, 7 December 2021 18:05:57 o'clock CET
*/

public interface calculOperations 
{
  void incrementer (org.omg.CORBA.IntHolder data);
  void decrementer (org.omg.CORBA.IntHolder data);
} // interface calculOperations
