package exo1;


/**
* exo1/calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/CHEDI/eclipse-workspace/exo1/src/spec.idl
* Wednesday, December 8, 2021 12:38:47 AM CET
*/

public interface calcul extends calculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul
